config/routes.rb
Rails.application.routes.draw do


  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  devise_scope :user do
    authenticated :user do
      # root to: 'students#home', constraints: ->(request) { get_user_class_from(request) == 'Student' }
      # root to: 'application_forms#index', constraints: ->(request) { get_user_class_from(request) == 'Staff' }
      # root to: 'students#home', constraints: ->(request) { request.env['warden'].user.class.name == 'Student' }
      # root to: 'staffs#homepage', constraints: ->(request) { request.env['warden'].user.class.name == 'Staff' }
      # root to: 'staffs#homepage', constraints: ->(request) { get_user_class_from(request) == 'Staff' }
      root 'admin#dashboard'
    end
    unauthenticated do
      root 'pages#home'
    end
  end

  get '/admin' => 'admin#dashboard'
  scope "/admin", module: 'admin', as: :admin do
    resources :staffs
    resources :clients
    resources :services
    resources :locations
    resources :bookings
    resources :customers
  end

  scope '/api', module: 'api', as: :api do
    resources :staffs, only: [:show]
    resources :bookings, only: [:create]
  end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/service.rb
# == Schema Information
#
# Table name: services
#
#  id         :bigint           not null, primary key
#  name       :string
#  price      :integer
#  detail     :text
#  duration   :integer
#  category   :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Service < ApplicationRecord
  has_many :booking_service_connects
  has_many :bookings, through: :booking_service_connects
end

app/controllers/admin/services_controller.rb
class Admin::ServicesController < AdminController
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  # GET /services
  def index
    @services = Service.all
  end

  # GET /services/1
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  def create
    @service = Service.new(service_params)

    if @service.save
      redirect_to @service, notice: 'Service was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /services/1
  def update
    if @service.update(service_params)
      redirect_to @service, notice: 'Service was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /services/1
  def destroy
    @service.destroy
    redirect_to services_url, notice: 'Service was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def service_params
      params.require(:service).permit(:name, :price, :detail, :time, :category)
    end
end

app/views/admin/services/_form.html.slim
- url = !!@service.id ? admin_service_path(@service) : admin_services_path
= simple_form_for @service, url: url do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :name
    = f.input :price
    = f.input :detail
    = f.input :duration
    = f.input :category

  .form-actions
    = f.button :submit, class: 'btn btn-success'

app/views/admin/services/edit.html.slim
h1 Editing service

== render 'form'

=> link_to 'Show', admin_service_path(@service)
'|
=< link_to 'Back', admin_services_path

app/views/admin/services/index.html.slim
h1 Listing services

table.table.table-sm
  thead
    tr
      th Name
      th Price
      th Detail
      th Duration
      th Category
      th
      th
      th

  tbody
    - @services.each do |service|
      tr
        td = service.name
        td = service.price
        td = service.detail
        td = service.duration
        td = service.category
        td = link_to 'Show', admin_service_path(service)
        td = link_to 'Edit', edit_admin_service_path(service)
        td = link_to 'Destroy', admin_service_path(service), data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Service', new_admin_service_path

app/views/admin/services/new.html.slim
h1 New service

== render 'form'

= link_to 'Back', admin_services_path

app/views/admin/services/show.html.slim
p#notice = notice

p
  strong Name:
  = @service.name
p
  strong Price:
  = @service.price
p
  strong Detail:
  = @service.detail
p
  strong Time:
  = @service.duration
p
  strong Category:
  = @service.category

=> link_to 'Edit', edit_admin_service_path(@service)
'|
=< link_to 'Back', admin_services_path