config/routes.rb
Rails.application.routes.draw do


  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  devise_scope :user do
    authenticated :user do
      # root to: 'students#home', constraints: ->(request) { get_user_class_from(request) == 'Student' }
      # root to: 'application_forms#index', constraints: ->(request) { get_user_class_from(request) == 'Staff' }
      # root to: 'students#home', constraints: ->(request) { request.env['warden'].user.class.name == 'Student' }
      # root to: 'staffs#homepage', constraints: ->(request) { request.env['warden'].user.class.name == 'Staff' }
      # root to: 'staffs#homepage', constraints: ->(request) { get_user_class_from(request) == 'Staff' }
      root 'admin#dashboard'
    end
    unauthenticated do
      root 'pages#home'
    end
  end

  get '/admin' => 'admin#dashboard'
  scope "/admin", module: 'admin', as: :admin do
    resources :staffs
    resources :clients
    resources :services
    resources :locations
    resources :bookings
    resources :customers
  end

  scope '/api', module: 'api', as: :api do
    resources :staffs, only: [:show]
    resources :bookings, only: [:create]
  end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/location.rb
# == Schema Information
#
# Table name: locations
#
#  id         :bigint           not null, primary key
#  name       :string
#  address    :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Location < ApplicationRecord
  has_many :staffs
end

app/controllers/admin/locations_controller.rb
class Admin::LocationsController < AdminController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  def index
    @locations = Location.all
  end

  # GET /locations/1
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  def create
    @location = Location.new(location_params)

    if @location.save
      redirect_to @location, notice: 'Location was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /locations/1
  def update
    if @location.update(location_params)
      redirect_to @location, notice: 'Location was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /locations/1
  def destroy
    @location.destroy
    redirect_to locations_url, notice: 'Location was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def location_params
      params.require(:location).permit(:name, :address)
    end
end

app/views/admin/locations/_form.html.slim
- url = !!@location.id ? admin_location_path(@location) : admin_locations_path
= simple_form_for @location, url: url do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :name
    = f.input :address

  .form-actions
    = f.button :submit, class: 'btn btn-success'

app/views/admin/locations/edit.html.slim
h1 Editing location

== render 'form'

=> link_to 'Show', admin_location_path(@location)
'|
=< link_to 'Back', admin_locations_path

app/views/admin/locations/index.html.slim
h1 Listing locations

table.table.table-sm
  thead
    tr
      th Name
      th Address
      th
      th
      th

  tbody
    - @locations.each do |location|
      tr
        td = location.name
        td = location.address
        td = link_to 'Show', admin_location_path(location)
        td = link_to 'Edit', edit_admin_location_path(location)
        td = link_to 'Destroy', admin_location_path(location), data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Location', new_admin_location_path

app/views/admin/locations/new.html.slim
h1 New location

== render 'form'

= link_to 'Back', locations_path

app/views/admin/locations/show.html.slim
p#notice = notice

p
  strong Name:
  = @location.name
p
  strong Address:
  = @location.address

=> link_to 'Edit', edit_admin_location_path(@location)
'|
=< link_to 'Back', admin_locations_path