config/routes.rb
Rails.application.routes.draw do


  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  devise_scope :user do
    authenticated :user do
      # root to: 'students#home', constraints: ->(request) { get_user_class_from(request) == 'Student' }
      # root to: 'application_forms#index', constraints: ->(request) { get_user_class_from(request) == 'Staff' }
      # root to: 'students#home', constraints: ->(request) { request.env['warden'].user.class.name == 'Student' }
      # root to: 'staffs#homepage', constraints: ->(request) { request.env['warden'].user.class.name == 'Staff' }
      # root to: 'staffs#homepage', constraints: ->(request) { get_user_class_from(request) == 'Staff' }
      root 'admin#dashboard'
    end
    unauthenticated do
      root 'pages#home'
    end
  end

  get '/admin' => 'admin#dashboard'
  scope "/admin", module: 'admin', as: :admin do
    resources :staffs
    resources :clients
    resources :services
    resources :locations
    resources :bookings
    resources :customers
  end

  scope '/api', module: 'api', as: :api do
    resources :staffs, only: [:show]
    resources :bookings, only: [:create]
  end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
# == Schema Information
#
# Table name: customers
#
#  id            :bigint           not null, primary key
#  name          :string
#  gender        :string
#  date_of_birth :date
#  phone         :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Customer < ApplicationRecord
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < AdminController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  def create
    @customer = Customer.new(customer_params)

    if @customer.save
      redirect_to @customer, notice: 'Customer was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /customers/1
  def update
    if @customer.update(customer_params)
      redirect_to @customer, notice: 'Customer was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /customers/1
  def destroy
    @customer.destroy
    redirect_to customers_url, notice: 'Customer was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def customer_params
      params.require(:customer).permit!
    end
end

app/views/admin/customers/_form.html.slim
- url = !!@customer.id ? admin_customer_path(@customer) : admin_customers_path
= simple_form_for @customer, url: url do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :name
    = f.input :phone
    = f.input :date_of_birth, as: :datepicker

  .form-actions
    = f.button :submit, class: 'btn btn-success'

app/views/admin/customers/edit.html.slim
h1 Editing customer

== render 'form'

=> link_to 'Show', admin_customer_path(@customer)
'|
=< link_to 'Back', admin_customers_path

app/views/admin/customers/index.html.slim
h1 Listing customers

table.table.table-sm
  thead
    tr
      th Name
      th Phone
      th Date of Birth
      th
      th
      th

  tbody
    - @customers.each do |customer|
      tr
        td = customer.name
        td = customer.phone
        td = customer.date_of_birth
        td = link_to 'Show', admin_customer_path(customer)
        td = link_to 'Edit', edit_admin_customer_path(customer)
        td = link_to 'Destroy', admin_customer_path(customer), data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Customer', new_admin_customer_path

app/views/admin/customers/new.html.slim
h1 New customer

== render 'form'

= link_to 'Back', customers_path

app/views/admin/customers/show.html.slim
p#notice = notice

p
  strong Name:
  = @customer.name
p
  strong Phone:
  = @customer.phone

=> link_to 'Edit', edit_admin_customer_path(@customer)
'|
=< link_to 'Back', admin_customers_path