config/routes.rb
Rails.application.routes.draw do


  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  devise_scope :user do
    authenticated :user do
      # root to: 'students#home', constraints: ->(request) { get_user_class_from(request) == 'Student' }
      # root to: 'application_forms#index', constraints: ->(request) { get_user_class_from(request) == 'Staff' }
      # root to: 'students#home', constraints: ->(request) { request.env['warden'].user.class.name == 'Student' }
      # root to: 'staffs#homepage', constraints: ->(request) { request.env['warden'].user.class.name == 'Staff' }
      # root to: 'staffs#homepage', constraints: ->(request) { get_user_class_from(request) == 'Staff' }
      root 'admin#dashboard'
    end
    unauthenticated do
      root 'pages#home'
    end
  end

  get '/admin' => 'admin#dashboard'
  scope "/admin", module: 'admin', as: :admin do
    resources :staffs
    resources :clients
    resources :services
    resources :locations
    resources :bookings
    resources :customers
  end

  scope '/api', module: 'api', as: :api do
    resources :staffs, only: [:show]
    resources :bookings, only: [:create]
  end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/client.rb
# == Schema Information
#
# Table name: public.clients
#
#  id         :bigint           not null, primary key
#  name       :string
#  subdomain  :string
#  industry   :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Client < ApplicationRecord
  after_create :create_schema

  def create_schema
    if subdomain && !Client.connection.schema_exists?(subdomain)
      ActiveRecord::Base.uncached do
        Apartment::Tenant.create(subdomain)
      end
    end
  end

  def switch!
    Apartment::Tenant.switch! subdomain
  end
end

app/controllers/admin/clients_controller.rb
class Admin::ClientsController < AdminController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  def index
    @clients = Client.all
  end

  # GET /clients/1
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  def create
    @client = Client.new(client_params)

    if @client.save
      redirect_to @client, notice: 'Client was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /clients/1
  def update
    if @client.update(client_params)
      redirect_to @client, notice: 'Client was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /clients/1
  def destroy
    @client.destroy
    redirect_to clients_url, notice: 'Client was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def client_params
      params.require(:client).permit(:name, :subdomain, :industry)
    end
end

app/views/clients/_form.html.slim
= form_for @client do |f|
  - if @client.errors.any?
    #error_explanation
      h2 = "#{pluralize(@client.errors.count, "error")} prohibited this client from being saved:"
      ul
        - @client.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :subdomain
    = f.text_field :subdomain
  .field
    = f.label :industry
    = f.text_field :industry
  .actions = f.submit

app/views/clients/edit.html.slim
h1 Editing client

== render 'form'

=> link_to 'Show', @client
'|
=< link_to 'Back', clients_path

app/views/clients/index.html.slim
h1 Listing clients

table
  thead
    tr
      th Name
      th Subdomain
      th Industry
      th
      th
      th

  tbody
    - @clients.each do |client|
      tr
        td = client.name
        td = client.subdomain
        td = client.industry
        td = link_to 'Show', client
        td = link_to 'Edit', edit_client_path(client)
        td = link_to 'Destroy', client, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Client', new_client_path

app/views/clients/new.html.slim
h1 New client

== render 'form'

= link_to 'Back', clients_path

app/views/clients/show.html.slim
p#notice = notice

p
  strong Name:
  = @client.name
p
  strong Subdomain:
  = @client.subdomain
p
  strong Industry:
  = @client.industry

=> link_to 'Edit', edit_client_path(@client)
'|
=< link_to 'Back', clients_path